version: '3'

services:
  katana:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    container_name: katana-crawler
    ports:
      - 8090:80
