version: '3'

services:
  katana:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    container_name: katana-crawler
    volumes:
      - type: bind  # Для результатов
        source: ./output
        target: /home/katana/output
    tty: true
